export const SETTINGS_KEYS = {
  cleanupAppAssignments: "cleanup_app_assignments",
  cleanupCustomPrompt: "cleanup_custom_prompt",
  cleanupEmailTone: "cleanup_email_tone",
  cleanupIntensity: "cleanup_intensity",
  cleanupOverallTone: "cleanup_overall_tone",
  cleanupPersonalTone: "cleanup_personal_tone",
  cleanupWorkTone: "cleanup_work_tone",
  remixHotkey: "remix_hotkey",
  contextEnabled: "context_enabled",
  contextSourceAccessibility: "context_source_accessibility",
  contextSourceEditor: "context_source_editor",
  contextSourceTerminal: "context_source_terminal",
  contextSourceWindow: "context_source_window",
  contextToAsr: "context_to_asr",
  contextToCleanup: "context_to_cleanup",
  freestyleCloudPanelExpanded: "freestyle_cloud_panel_expanded",
  hotkey: "hotkey",
  hotkeyMode: "hotkey_mode",
  historyPaused: "history_paused",
  historyRetentionDays: "history_retention_days",
  // Legacy singular language key. Kept for one-time migration reads only;
  // the canonical setting is now `languages` (a JSON array of ISO codes).
  language: "language",
  languages: "languages",
  llmCleanup: "llm_cleanup",
  localLlmApiKey: "local_llm_api_key",
  localLlmUrl: "local_llm_url",
  micDeviceId: "mic_device_id",
  mlxAsrKeepAliveMinutes: "mlx_asr_keep_alive_minutes",
  networkCaCertPath: "network_ca_cert_path",
  networkProxyUrl: "network_proxy_url",
  outputMode: "output_mode",
  openaiSttApiKey: "openai_stt_api_key",
  openaiSttBaseUrl: "openai_stt_base_url",
  dictationDestination: "dictation_destination",
  soundEnabled: "sound_enabled",
  translateMode: "translate_mode",
} as const;

export type SettingsKey = (typeof SETTINGS_KEYS)[keyof typeof SETTINGS_KEYS];
